apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
spec:
  containers:
  - name: my-container
    image: nginx
  - name: sidecar-container
    image: busybox 
    command: ['sh', '-c', 'echo Hello from the sidecar container! && sleep 3600']